### ISSUE TITLE
Allfiles?

### ISSUE THREAD

**Issue by psanford89** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#10]
Is this repository supposed to have anything in the allfiles folder. The allfiles folder I got is empty. 
I used the pandoc script provided.

**Comment by mdwoernhard** [comment]
The pandoc.ps1 creates a ZIP file in the BUILD folder with the generated Word-files.

**Comment by psanford89** [comment]
Ok. Just to clarify. There are two zip files created. One allfiles zip and one lab instructions zip. The allfiles zip was empty and the lab instructions zip has the Word-files in it. Is this correct?

**Comment by mdwoernhard** [comment]
The allfiles zip contains all external files like CSV, PowerShell Scripts etc. The allfiles zip file is empty because there is no "Allfiles" folder for 10997 (would be on the same level as Build and Instruction).

**Comment by ddamir76** [comment]
Yes, no Allfiles for this course, so you can ignore this error.
