### ISSUE TITLE
Suggested Edits for 10997

### ISSUE THREAD

**Issue by XtremeMichaelRogers** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#20]
Hello All,
I just finished a run through of this course and there were a couple of things I wanted to note.   

Going through Module 5, Skype for Business Administration, it appears that Microsoft has rolled out a new UI for the Skype for Business admin section of O365 (it's not even called that anymore).  While there is a legacy portal option available that matches the UI described in the instructions it might be helpful to re-write this section to match the new UI.  

Also, in Module 8, managing security, it looks like the Security and Compliance center no longer matches the UI described in the answer key, to quite a large extent.  I was only able to find some of the options and features needed to perform the lab steps and I was often left to guess how to configure certain areas that have been updated or altered.  This entire section of the O365 portal is very confusing, and some up to date or at least more informative navigation instructions would really help out.  

Thank you for your consideration.

**Comment by ddamir76** [comment]
Course is now being updated. All these issues (and many others) will be addressed. Thanks!
