### ISSUE TITLE
AllFiles folder Missing

### ISSUE THREAD

**Issue by yonatanbt2** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#24]
The powershell script fails with errors when I try to convert the lab files to Word. On further investigation I found out that the AllFiles folder which is required is missing. Please Advise.

**Comment by ddamir76** [comment]
This course does not have Allfiles folder.
Thanks for reporting!

**Comment by yonatanbt2** [comment]
Thank you for your reply. Does this mean we cannot convert this the .md files to word?

**Comment by ddamir76** [comment]
Of course not. You can run pandoc script and it will covert all md files. It will just report error for Allfiles folder.

**Comment by itbland** [comment]
@ddamir76, in some of the other classes where this happens, a place-holder folder and a text file explaining that there are no other files is created to help keep the confusion level down. 
Just my $.02.

**Comment by ddamir76** [comment]
Thanks for your suggestion. We are now working on updating this course, will make sure that this is updated also.
