### ISSUE TITLE
Suggested edit for 10997\build\pandoc.ps1

### ISSUE THREAD

**Issue by luconsta** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#25]
Hello Everyone,
I had a problem compiling the files using the .build\pandoc.ps1 script - it let winword.exe processes open for each .md file.
The problem seems to be in the **AddVersionFooter** function that didn't quit the Word app. Adding these 2 lines at its end it seems to solve the problem:
```
$Word.Quit()
$Word=$null
```

Kind regards,
Lucian

**Comment by ddamir76** [comment]
Thanks very much for reporting this issue. We will investigate it, and will update the script if we reproduce this problem.
