### ISSUE TITLE
missing ps1 files

### ISSUE THREAD

**Issue by onderkokturk1** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#26]
Hello
I can't find lab ps1 files. for example 
LAB4:	Task 1: Generate a problem
1.	Open Windows Azure Active Directory Module for Windows PowerShell with administrative privileges.
2.	Execute the **Mod4_CreateProblem.ps1** script from the C:\LabFiles\Mod04 folder.
do you have any idea?
thanks

**Comment by ddamir76** [comment]
Hello,
Are you sure that you are on the right VM? I just checked, this file is present in this location, on LON-CL1 machine.

**Comment by onderkokturk1** [comment]
Hi @ddamir76  
yes I found it. thank you so much
