### ISSUE TITLE
Module 8 Security and Compliance

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#27]
The lab steps need updating to either reflect the new separate security and compliance centers with steps indicating where students should go to. Or, a reference to the fact they should use protection.office.com when instructed to go to 'security and compliance center'. Of course, this may not work in the long-run.

Specifically, Exercise 2, Task 1, Step 4. There is only 'Security' and 'Compliance' as distinct entities.

The same issues exist in multiple steps from there down due to references to 'security and compliance center' references.

**Comment by ddamir76** [comment]
Thanks for reporting this. I made a quick fix with URL protection.office.com, but will plan to update this to new portals.
