### ISSUE TITLE
Module 3 Exercise 4 LAK needs more details instructions

### ISSUE THREAD

**Issue by XtremeDR** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#28]
When performing Module 3 Task 4, both of these tasks, running the script and using IdFix, need to be done by the domain administrator.  While the Lab Steps document does make this clear, the LAK does not, it asks the user to be signed in as Holly if at all.  While a user can probably figure it out based on the error messages they are given it might be a good idea to add steps informing the user to ensure they are logged in as Adatum\Administrator.  

Also, since the latest VMs for this course lock the domain admin out of using Edge, the user will have to search for iexplore.exe to find Internet Explorer so they can download IdFix unless they want to sign in and out of the Holly account for this part of the task.

**Comment by ddamir76** [comment]
Thanks for reporting this. I added some more info in the first step.
