### ISSUE TITLE
Module 8 Azure Information Protection

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#3]
Instructions should be updated to use the AADRM module. Set-IRMConfugaration doesn't work anymore.

**Comment by ddamir76** [comment]
I retested this whole lab, and can't reproduce this issue. For the tenant I created and used, Set-IRMConfiguration worked just fine. See the capture. What error did you get?
![capture](https://user-images.githubusercontent.com/36815646/37555150-e3e8cff2-29da-11e8-878a-cbca1fe4fc00.PNG)

**Comment by itbland** [comment]
FYI: https://github.com/MicrosoftLearning/20347-Enabling-and-Managing-Office365/issues/72

**Comment by molenaar** [comment]
It happened on new created tenants in UK and us. Even my existing tenant shows that the set-irmconfigurarion command is deprecated. Learn On Demand has updated  instructions in their 10997 course that work.

**Comment by molenaar** [comment]
It is exactly that latest screenshot you uploaded. The link doesn’t work btw.
