### ISSUE TITLE
Cannot send mails from onmicrosoft.com domains

### ISSUE THREAD

**Issue by Rokory** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#31]
All mails send from the default adatumyyxxxx.onmicrosoft.com domain bounce, event e-mails sent to internal users. The labs should mention that this problem does not exist, if a custom domain ist added.

**Comment by ddamir76** [comment]
I can't reproduce this. Are you sure that this happens with all emails? We never had this type of issue reported.

**Comment by Rokory** [comment]
We had this with all participants of my last course, including my account. Maybe it has something to do with the term adatum*.

It seems to be quite a common problem, so common, that even a Microsoft blog article discusses it. Here is the reference:

https://blogs.technet.microsoft.com/latam/2016/12/13/o365-spam-abuse-ndr/

In course 20347, participants register a custom domain, therefore I was not aware of the problem, as this was my first 10997. But the course design should consider this. I do not have an easy solution. Maybe, a custom domain should be registered for this course too. Or a different name than adatum (maybe chosen by the participants) fixes the problem. Or make the labs not dependent on sending an receiving mails. IDK.

**Comment by itbland** [comment]
5/17/2019 10997B, Mod 06, when sharing the SharePoint site and then sharing the document--the Site email was delivered but the document sharing email was refused by Outlook.com as SPAM:

> Remote Server returned '550 5.7.501 Service unavailable. Spam abuse detected from IP range.

So it may be that some of the Office 365 mail servers are ending up on RBLs and it may be somewhat random. 
(C'mon MS, blocking your own servers?!?)

**Comment by ddamir76** [comment]
Thanks for reporting and investigating this. This type of issue is beyond my capabilities to resolve. I will try to escalate to MS.

**Comment by Rokory** [comment]
I think, the best solution would be to change the course design and let the students apply a custom domain to their tenants, like in course 20347.

**Comment by ddamir76** [comment]
Just a quick update - this course will most likely be updated in coming weeks. As a part of update, this issue will be resolved. Thanks for reporting.
