### ISSUE TITLE
Module 8 - Security and Compliance

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#33]
Howdy,

This module is now totally broken in terms of the lab steps. Even with the changes to URL. Many steps now can't be completed.

**Comment by ddamir76** [comment]
Hi. Thanks for reporting this. This course is about to be updated very soon, so this issue will be fixed.

**Comment by WigF1** [comment]
And here we are almost 3 months later with no fix and no 'C' version.
