### ISSUE TITLE
Only 5 Licenses!!!

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#35]
This week, only 5 licenses are available in the trial account!!! (If this is the new normal, it will affect the new "C" Labs also!)

**Comment by itbland** [comment]
Update: This week, the Learn on Demand labs have only 5 Office 365 E5 **_Demo_** licenses. Temporary solution: added Microsoft 365 E5 trial subscription with 25 more licenses.

**Comment by AnnetteGill** [comment]
Please can Microsoft sort this out?  It's ridiculous that they would restrict students to 5 licences, when the lab instructions call for 13 licences!

**Comment by ddamir76** [comment]
Hello,
Thanks for reporting this issues. I just created a new trial Office 365 E5 trial tenant, and I got 25 licenses as before. Did you select 250-999 for the company size when creating trial tenant? Can you please try again? We need to be able to reproduce this before I can escalate to WWL.

**Comment by normandk** [comment]
This is an issue based on the auto provisioned 375 accounts we get from
Labs On Demamd.  I taught the Ms-500 class this week and had the same issue
of 5 licenses but needing more.   I opened a ticket with LOD on Monday and
today got the following reply....

"The WWL stakeholders adjusted the tenant SKUs used for MOC labs: we have
reached out to them to let them know this has caused an issue for some
labs, but in the meantime, you should be able to get around it by having
the students add a Microsoft E3 trials to their tenant."

**Comment by itbland** [comment]
[Training Support Issue](https://trainingsupport.microsoft.com/en-us/tcmct/forum/tcmct_moc/10997-only-5-licences-in-office-365-tenant/653c8045-5827-468e-9f33-46895ef3d9a3?messageId=943a2870-95e4-4212-8f2a-001c44a4b7ba)

> Merrick Van Dongen_Test 
Replied on August 15, 2019 
Microsoft Employee 
Yes, thanks for the timely feedback and apologies for the churn and dissat this is causing.  We recently discovered that while transitioning to a different partner providing Microsoft with tenants for this course, that the licenses provisioned for this tenant changed from 25 to 5 Office 365 licenses.  We have since sought and received approval from the Office Business Group to provide tenants with enough licenses to support the labs in this course.  We are working through that process now and trying to re-provision new tenants asap.  We will be working with LODS and our other Authorized Lab Hosters to handle this provisioning.
