### ISSUE TITLE
Out of date instructions

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#36]
Mod 8 Ex 2 includes the following instruction

"On LON-CL1, open Microsoft Edge, and then sign in to Microsoft 365 admin center as Holly@Adatumyyxxxxx.onmicrosoft.com and navigate to Security & Compliance admin center.

Make sure that you opened the Office 365 Security & Compliance Center."

The Security & Compliance Center was replaced with the new Security Center & the new Compliance Center months ago.
Why is this version, released 4 months after the change to the portal still using out of date interfaces?

**Comment by ddamir76** [comment]
Hello. Thanks for your feedback. Currently, this is still not consistent, and on some newly created tenants we still have just one center for Security & Compliance. I will try to find out who Microsoft plans to handle this in future, and steps will be updated accordingly.

**Comment by djcmct** [comment]
Would it not then make more sense to direct people to https://protection.office.com instead until this inconsistency was resolved?

**Comment by grantcarthew** [comment]
@ddamir76 it is not normal to close issues unless they are rectified.

**Comment by ddamir76** [comment]
At this point, I still can't confirm that we have an issue, because we are still seeing Security & Compliance portal in tenants created when the lab for the course is provisioned. I can keep this open, however.

**Comment by itbland** [comment]
If a student chooses US as the location, you ALWAYS see the two different admin centers, If they choose UK (per instructions) you see Security & Compliance.
Learn On Demand (we use) has used US location for their labs and we see the two different Admin centers.

________________________________

**Comment by ddamir76** [comment]
Lab steps to access Office 365 Security and Compliance center are now updated. Also, few other changes for Module 8 are incorporated to address latest UI changes. Thanks for your patience.
