### ISSUE TITLE
PSCX Still required?

### ISSUE THREAD

**Issue by chwilfing** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#37]
The PSCX extension is still required even if the download is blocked by Edge (screenshot attached: 
![image](https://user-images.githubusercontent.com/16267927/66733673-95435600-ee60-11e9-878c-172f4cd37e54.png) ) 

the files are hosted on codeplex (which is deprecated...) and the build process is cumbersome. Even if the PSCX requirement is only based on the Write-ZIP Cmdlet. if this is removed, the build process does work as far as I see...

why not use the great feature of YAML files to provide a sample build pipeline? I'd love to use my own Azure DevOps Account to import the YAML pipeline it's just everytime I need I've to install pandoc on my own machine,...

**Comment by ddamir76** [comment]
Thanks for your feedback. I have to check this with Microsoft Learning, and will get back to you.

**Comment by itbland** [comment]
PSCX is now hosted in the PowerShell Gallery, to install just use:
Install-Module -Name Pscx

________________________________

**Comment by ddamir76** [comment]
This is exactly what we have in MCT guide. I think that no action is required here.
