### ISSUE TITLE
LAB5|Exercise 1|Task 3/Task 5: Teams Island Mode no longer available

### ISSUE THREAD

**Issue by chwilfing** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#39]
Tenant provisioned in Europe - Teams Upgrade mode is no longer available. 
![image](https://user-images.githubusercontent.com/16267927/66903694-39fd9900-f003-11e9-98d4-a47b84437322.png)

https://github.com/MicrosoftLearning/10997-O365AdministrationandTroubleshooting/blob/10997C/Instructions/10997C_LAB_05.md

Also - Task 5 is not possible due to missing Teams Upgrade Modes in new Tenant

**Comment by ddamir76** [comment]
Thanks for your feedback. I will verify lab steps on the latest M365 tenants and will update as needed.

**Comment by ddamir76** [comment]
Steps for Skype/Teams module are updated to reflect latest UI and functional changes for these services.
