### ISSUE TITLE
Lab instructions out of date

### ISSUE THREAD

**Issue by theterminator3000** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#40]
Just done a course and some of the documentation is out of date as there have been some major design changes since the last commit

**Comment by ddamir76** [comment]
Hello,
Thanks for your feedback. Can you please provide few examples of UI inaccuracies that you experienced, so we can fix it? Or at least provide info about module where you had these issues?

**Comment by theterminator3000** [comment]
Hi, sorry there is quite a few. The recent one I can remember is that on module 6 it mentions clicking sharing which is actually now located under Policies. I'll try and run back through the labs to see what else is different

**Comment by ddamir76** [comment]
Thanks. I will check Module 6 lab. If you have info about other modules also, please let me know.

**Comment by ddamir76** [comment]
UI changes in Module 6 are now fixed. Please report if you notice more bugs in lab steps. Thanks!
