### ISSUE TITLE
C:\Labfiles\Mod07\Mod7_CreateProblem.ps1 errors

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#42]
LabOnDemand just switched to the newer "**C**" version of the VMs and the **Mod7_CreateProblem.ps1 script** fails with several errors:

1. Because a Microsoft 365 license is used, the loop executed in **lines 17-21** generates 2 errors for the EMS and Win10 licenses , but succeeds on the Office 365 E5 license.
2. The Invoke-Command in **lines 23-25** fails because the **C:\Labfiles folder _is not shared_ on LON-CL1** (Is this an error in the VM or did _LabOnDemand_ make this mistake in setup?)
3. **Lines 27-29** fail because they are run on LON-CL1 by Holly; in the 10997B version of the script, these last three lines were run in a: 

> New-PSSession -ComputerName LON-DC1 -Credential Adatum\Administrator

This line is missing in the new script.

**Comment by ddamir76** [comment]
Thanks for the bug report. I didn't see this issue so far, no other MCT reported this. I will run this lab in our test environment to see if I can reproduce this. I will get back to you once I retest this. As this course uses tenants that ALH precreates, I've seen some issues as some of them uses M365 tenants and some uses O365 tenants.

**Comment by itbland** [comment]
A little more information:
1. To filter for Office 365 E3, Office 365 E5, Microsoft 365 E3, or Microsoft 365 E5, we could change line 15 of the script to:

`$AllLicensingPlans = Get-MsolAccountSku | Where-Object { ($_.AccountSkuId -contains "Enterprise") -or ($_.AccountSkuId -like "SPE*") }`

2. I checked the Xtreme lab and the C:\Labfiles folder is not shared.

**Comment by itbland** [comment]
Sample file (without the signature block), I included sharing the C:\Labfiles folder.
[Mod7_CreateProblem.txt](https://github.com/MicrosoftLearning/10997-O365AdministrationandTroubleshooting/files/4319630/Mod7_CreateProblem.txt)

**Comment by ddamir76** [comment]
Thanks! We will probably require a new VM build for this. Let me check if we can do it now

**Comment by TesterTesterson1004** [comment]
Is there any movement on this issue?  

I am not a scripting expert, however after some testing using LODS hosted environment of 10997C, and receiving various errors using both the supplied 'Mod7_CreateProblem.ps1' and the one referenced in this thread 'Mod7_CreateProblem.txt', I ended up with the attached version that *appears* to work, although I need to run it through a complete end-to-end to be 100% certain.

I would much prefer the script provided in the downloads functions, however.  :)
[Mod7_CreateProblem_Test.txt](https://github.com/MicrosoftLearning/10997-O365AdministrationandTroubleshooting/files/4766195/Mod7_CreateProblem_Test.txt)

**Comment by ddamir76** [comment]
Hello,
We should have info pretty soon about if MS will update this course or not. If course is being updated, new VM build will be delivered and this fix will be applied. If not, we will provide an error log with instructions on how to fix. Thanks for your patience.
