### ISSUE TITLE
Why aren't we changing the UPN suffixes in Adatum.com?

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#43]
In the 10997C_LAB_AK_03, Exercise 2, Task 1, we manually change the  domain of some of the sync-ed users. Why don't we change the UPN suffix on LON-DC1 before we install AD Connect per the documentation at [Prepare a non-routable domain for directory synchronization](https://docs.microsoft.com/en-us/office365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization#add-upn-suffixes-and-update-your-users-to-them)? Isn't this a best practice? (Isn't this what we did in previous versions?)

**Comment by ddamir76** [comment]
Thanks for the comment. You probably talk about procedure that we have in 20347 course where we changed the UPN with a script. As I can recall, we didn't do this in this course. However, I will consider that option for the next update.
