### ISSUE TITLE
Mod 08 Lab, Office not installed on LON-CL2

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#45]
At the end of the Mod 07 lab, we have used the create problem script to uninstall Office Pro Plus from both LON-CL2 and LON-CL3, and unlink the DeployO365 GPO. We fix the GPO and restart LON-CL3, but we do not explicitly re-install Office on LON-CL2, which is needed at the end of the Mod 08 Lab.

**Comment by ddamir76** [comment]
Fixed as suggested. Thanks!
