### ISSUE TITLE
Module 5 Admin Centre Changes

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#50]
Legacy portal is no longer present in the Teams Admin Centre.

Could the lab instructions be updated to reflect the change?

**Comment by ddamir76** [comment]
Hello,
We are about to release D version of this course in a couple of days, with a lot of updates.
Thanks!

**Comment by djcmct** [comment]
Would you like to share the date the the D version will be released?

As MSL seems to have stopped releasing the courseware title plan we're all a little in the dark as to new/changed anything.

As it stands, the C version labs don't work and this is the only version we have access to

**Comment by normandk** [comment]
The CW title plan is in the resources section (lower right) of MCT Central home page ( https://www.microsoft.com/en-us/learning/mct-central.aspx )  According to it, D version date is Feb 5, 2021.

**Comment by djcmct** [comment]
> The CW title plan is in the resources section (lower right) of MCT Central home page ( https://www.microsoft.com/en-us/learning/mct-central.aspx ) According to it, D version date is Feb 5, 2021.

That's November's update, we're missing December's, (hence comment around stopped releasing), dates have a habit of changing, so all i'm asking for is clarity on release date, according to reply above, release of D "in a couple of days", our scheduling team need a little more clarity :)
