### ISSUE TITLE
Mod 6 Lab Classic Portal Gone

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#53]
Mod 6 Lab Classic Portal Gone

Exercice 2 
Task 1 
Skip step 1 to 3
Replace with these steps

Goto Sharepoint Admin, Click Sites / Active Sites
Choose + Create, Select Other Options, Under Choose Template Select More Templates

Goto Step 4

At Step 6 Click Go to the Active sites page

At Step 7 Click the radio button to right of site and Sharing at top appears

At Step 9 Click Radio Button Anyone, Save

**Comment by ddamir76** [comment]
Thanks for reporting this. We will investigate, and will fix as needed.

**Comment by ddamir76** [comment]
We investigated this issue, and couldn't replicate. Will try to replicate, maybe it is tenant related. Thanks.
