### ISSUE TITLE
 **CL1** it doesn't have Windows Server Tools loaded

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#55]
# Exercise 1 
### Step 14

**CL1** it doesn't have Windows Server Tools loaded

https://github.com/MicrosoftLearning/10997-O365AdministrationandTroubleshooting/blob/10997D/Instructions/10997D_LAB_01.md#task-2-add-a-custom-domain-and-verify-ownership

**Comment by ddamir76** [comment]
Thanks for reporting this. We didn't experience this during the course test, so we will check with lab hosting providers if they built VMs according to instructions.

**Comment by ITBlandMCT** [comment]
Can confirm this is also a problem with Go Deploy labs, in addition Holly is not an admin in AD DS, so the corrections in IDFix can't be applied.
Quick fix: Don't sign in as Holly on CL1 until Lab 4, and run this command before running the script:
`Add-WindowsCapability -Online -Name Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0`

**Comment by ddamir76** [comment]
Labs steps in modules 1 and 3 are now updated to include installation of RSAT tools on LON-CL1, as well as changing sign in name for Lab 3, Ex4. Thanks!
