### ISSUE TITLE
This lab comes with an E5 tenant but has instructions to start a free trial

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#56]
The **tenant** already comes with **15 E5 licenses** and **E3 licenses**; yet the instructions call for you to create a **trial account**.  When you attempt to run with the tenant, the steps in this section https://github.com/MicrosoftLearning/10997-O365AdministrationandTroubleshooting/blob/10997D/Instructions/10997D_LAB_AK_01.md#task-1-create-an-office-365-e5-trial-subscription do not line up. 
Should these steps be skipped if a tenant was provided?

**Comment by ddamir76** [comment]
Labs in this course are designed to work on newly created E5 trial tenant, as not all ALHs provision Office 365 tenant. Most of the lab steps will also work in pre-provisioned tenant, but on few places some workarounds are needed.
