### ISSUE TITLE
10997 Lab 8

### ISSUE THREAD

**Issue by grantcarthew** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#7]
Having issues enabling RMS:

```sh

PS C:\Users\Administrator> Set-IRMConfiguration -RMSOnlineKeySharingLocation "https://sp-rms.ap.aadrm.com/TenantManagement/ServicePartner.svc"
The Trusted Publishing Domain (TPD) for your organization should be managed in Microsoft Azure Rights Management.  The 'RMSOnlineKeySharingLocation' parameter has
been deprecated.  For more information, see http://go.microsoft.com/fwlink/p/?LinkId=789272.
    + CategoryInfo          : InvalidArgument: (:) [Set-IRMConfiguration], LocalizedException
    + FullyQualifiedErrorId : [Server=CWXP265MB0886,RequestId=068b8553-d364-4023-a78b-dfffa299b70f,TimeStamp=8/06/2018 6:23:12 AM] [FailureCategory=Cmdlet-Localized
   Exception] 612DECAE,Microsoft.Exchange.Management.RightsManagement.SetIRMConfiguration
    + PSComputerName        : outlook.office365.com
```

**Comment by grantcarthew** [comment]
Looks like it is activated already:

https://docs.microsoft.com/en-us/azure/information-protection/deploy-use/activate-service

> If your subscription that includes Azure Rights Management or Azure Information Protection was obtained towards the end of February 2018 or later, the service is automatically activated for you. You do not have to activate the service unless you or another global administrator for your organization deactivated Azure Rights Management.

**Comment by ddamir76** [comment]
Hello. Thanks for your comment. In a step before this one there is note to skip the activation if you successfully verify that service is activated. Were you able to do that?

**Comment by grantcarthew** [comment]
You're right @ddamir76 about the steps. Not sure if the values came back true or not. Closing.
