### ISSUE TITLE
Crippled paths due to unescaped backslashes (Module 3, 4, 6, 7, 8 including Answer Keys)

### ISSUE THREAD

**Issue by mdwoernhard** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#8]
There are several rendering issues with backslashes in the lab and lab answer keys files. Given how pandoc interprets the Markdown content the paths are crippled and leave learners confused and stumped.

There's a list of lines with unescaped backslashes

```
Instructions\10997A_LAB_03.md(278)
Instructions\10997A_LAB_03.md(297)
Instructions\10997A_LAB_04.md(305)
Instructions\10997A_LAB_04.md(358)
Instructions\10997A_LAB_06.md(346)
Instructions\10997A_LAB_07.md(96)
Instructions\10997A_LAB_07.md(104)
Instructions\10997A_LAB_07.md(321)
Instructions\10997A_LAB_08.md(494)
Instructions\10997A_LAB_08.md(506)
Instructions\10997A_LAB_AK_03.md(144)
Instructions\10997A_LAB_AK_03.md(309)
Instructions\10997A_LAB_AK_03.md(351)
Instructions\10997A_LAB_AK_03.md(353)
Instructions\10997A_LAB_AK_03.md(375)
Instructions\10997A_LAB_AK_04.md(318)
Instructions\10997A_LAB_AK_04.md(375)
Instructions\10997A_LAB_AK_06.md(445)
Instructions\10997A_LAB_AK_07.md(464)
Instructions\10997A_LAB_AK_08.md(608)
Instructions\10997A_LAB_AK_08.md(630)
Instructions\10997A_LAB_07.md(98)
Instructions\10997A_LAB_07.md(108)
Instructions\10997A_LAB_07.md(252)
Instructions\10997A_LAB_AK_03.md(144)
Instructions\10997A_LAB_AK_03.md(351)
Instructions\10997A_LAB_AK_03.md(353)
Instructions\10997A_LAB_AK_03.md(375)
Instructions\10997A_LAB_AK_04.md(375)
Instructions\10997A_LAB_AK_04.md(377)
Instructions\10997A_LAB_AK_07.md(53)
Instructions\10997A_LAB_AK_07.md(76)
Instructions\10997A_LAB_AK_07.md(110)
Instructions\10997A_LAB_AK_07.md(363)
```

I suggest escaping the whole path expressions with backticks, instead of escaping only the backslashes.

Since I have fixed all of these occurences in my cloned repo I would have loved to create a PR, but this does not seem possible. If it is possible, please provide help on how to submit a RP for this repo.

**Comment by ddamir76** [comment]
Thanks for reporting this. I'm not able to give you permission to do PR, but I can do it for you. can you please provide me an example how you fixed these issues in your repo?

**Comment by mdwoernhard** [comment]
I did a simple search and replace. First run: replace double backslashes with quad-backslashes (\\ -> \\\\, this takes care of the UNC paths), second run: replace single backslashed with double backslashes (this takes care of the paths and sign-in information)

-------- Forwarded Message --------
Subject:

Re: [MicrosoftLearning/10997-O365AdministrationandTroubleshooting] Crippled paths due to unescaped backslashes (Module 3, 4, 6, 7, 8 including Answer Keys) (#8)

Date:

Sat, 07 Jul 2018 05:02:49 -0700

From:

ddamir76 <notifications@github.com><mailto:notifications@github.com>

Reply-To:

MicrosoftLearning/10997-O365AdministrationandTroubleshooting <reply@reply.github.com><mailto:reply@reply.github.com>

To:

MicrosoftLearning/10997-O365AdministrationandTroubleshooting <10997-O365AdministrationandTroubleshooting@noreply.github.com><mailto:10997-O365AdministrationandTroubleshooting@noreply.github.com>

CC:

mdwoernhard <maurice@woernhard.net><mailto:maurice@woernhard.net>, Author <author@noreply.github.com><mailto:author@noreply.github.com>



Thanks for reporting this. I'm not able to give you permission to do PR, but I can do it for you. can you please provide me an example how you fixed these issues in your repo?

**Comment by ddamir76** [comment]
This is fixed now. Thanks itbland.
